### ISSUE TITLE
feature request - option to highlight the whole row

### ISSUE THREAD

**Issue by guidopatanella** [jisaacks/GitGutter#216]
This request is inspired on NetBeans IDE. For instance, when there are changes, the whole row is highlighted to:
- light green for additions
- yellow for modifications
- rose for deletions

This higly improves readability. I realize the various color schemes make it difficult, although colors might be simply a part of the settings for advanced purposes

**Comment by dbergey** [comment]
+1

**Comment by deathaxe** [comment]
This will depend on color schemes, too. I saw several color schemes showing added and modified lines with the same color. Marking the whole line is not a problem at all.

**Comment by jisaacks** [comment]
I looked into this when originally building gitgutter. I was unable to add a background while maintaining syntax highlighting. I thought syntax highlighting was more important. That was a few years ago so it may be possible now?

**Comment by deathaxe** [comment]
Loosing syntax highlighting is the drawback of marking the whole line, but this could be user's choice. I like the current solution and find marking the whole line looks not so good, but as it is no big effort, I could imagine to implement it.

But basically it's the same thing as with the size of gutter icons. It is basically ok on "normal" displays, but due to a lack of correct scaling those elements become nearly invisible on the new 12" 4K/8K... life style ultrabook displays.

**Comment by jisaacks** [comment]
I dunno, I think if we add a feature that allows them to use their own icons, which I think we are considering, they would have a lot of freedom. I am afraid of getting too bloated by just implementing everything under the sun, even if it's not very useful.

@r-stein @rchl thoughts?

**Comment by r-stein** [comment]
I don't think it is worth for enough people to have the background on the cost of syntax highlighting. Git is mostly used together with source code, hence syntax highlighting is important.
One could make a border around the lines, but then we would fight with other packages over that region highlighting and not only over the gutter icons. I would not want to provide support for the resulting issues.
