### ISSUE TITLE
GitGitter crashes my ST3 when I switch branches in Tower.

### ISSUE THREAD

**Issue by tzvigqb** [jisaacks/GitGutter#232]
When I switch branches in Tower, I get a message that the plugin host has crashed, and plugins wont work until sublime has been restarted.

**Comment by jisaacks** [comment]
If you disable git gutter does the issue go away?

**Comment by tzvigqb** [comment]
Yes

On Tue, May 26, 2015 at 11:29 AM, JD Isaacks <notifications@github.com>
wrote:

> If you disable git gutter does the issue go away?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jisaacks/GitGutter/issues/232#issuecomment-105568363>.
>



-- 
Tzvi Gershbaum

Qualitybath.com
Front End Developer

**Comment by hbridge** [comment]
+1 I'm seeing my plugin-host crash in ST3 after I do a git rebase.  Disabling GitGutter makes it go away.

**Comment by tzvigqb** [comment]
@hbridge I've found that setting `"live_mode": false` corrects the plugin host crashing issue for me.

**Comment by hbridge** [comment]
Thanks will give it a try!

**Comment by hbridge** [comment]
Disabling live mode worked for awhile, but for some reason a couple of weeks ago the crash started happening again when I would foreground ST3.  Setting ```"focus_change_mode": false``` fixes it, but makes GitGutter much less useful.  Are there any logs I can gather to help fix this?

**Comment by rchl** [comment]
Sorry but I can't see what can be done about it. There is nothing in this package than can make it crash. The only thing that can crash is the git itself (taking down plugin host with it) so the problem is not really on the package side. Should maybe try newer git version or something.

If this crash was more likely to be triggered with `focus_change_mode: true` then it might be that it will be better with current master which uses async invocations. But if git is crashing then not much can be done about it here.
