### ISSUE TITLE
Change marks not clearly visible on the minimap

### ISSUE THREAD

**Issue by azdavis** [jisaacks/GitGutter#263]
<img width="1280" alt="screen shot 2015-12-30 at 8 27 55 pm" src="https://cloud.githubusercontent.com/assets/6496454/12059962/dcb3e272-af33-11e5-9451-26fc6cf790c7.png">

I verified the default settings have `"show_in_minimap": true` and even added this to my own user settings. No dice.

| thing | version |
| :-- | :-- |
| GitGutter | 1.2.2 |
| Sublime Text | 3 (dev build 3095) |
| OS X | 10.11.2 (build 15C50) |

**Comment by AviBueno** [comment]
Same issue on Win 8.1, Git Gutter 1.2.2, Sublime Text 3 stable build v3083.

**Comment by jisaacks** [comment]
@azdavis @AviBueno Is it not working at all or just under certain circumstances?

**Comment by azdavis** [comment]
I've done some experimentation.

Adding lines with text, it seems as though the green bar is actually behind the text.
<img width="162" alt="img_1" src="https://cloud.githubusercontent.com/assets/6496454/12126121/4c950412-b3bd-11e5-9a39-a53787a7c289.png">
This problem, as one might expect, does not manifest when the added lines have no text of their own.
<img width="171" alt="img_2" src="https://cloud.githubusercontent.com/assets/6496454/12126148/6cb320d0-b3bd-11e5-8092-426508c0c157.png">
I thought maybe if I added or modified lines with indentation, this problem would be avoided. No dice.
<img width="1280" alt="img_3" src="https://cloud.githubusercontent.com/assets/6496454/12126166/855698a6-b3bd-11e5-8e8a-c92db0df7c46.png">
But then I deselected that which I had indented…
<img width="1280" alt="img_4" src="https://cloud.githubusercontent.com/assets/6496454/12126176/91a99f5e-b3bd-11e5-9a28-34c4e2d4a58a.png">
Odd indeed.

**Comment by AviBueno** [comment]
Sorry, I have GitGutter installed for a long time but only yesterday I discovered it can show up on the minimap. This was after I saw the Atom equivalent on a friend's machine. So I looked at the minimap but didn't see anything.
Following @azdavis reply I only now realized it's a 1 pixel thingy (was expecting a fully colored line).

I tested now and I guess it works, although it's almost impossible to see any indication.
![image](https://cloud.githubusercontent.com/assets/5699730/12127704/5b2c63d2-b401-11e5-8807-3ee3e445409d.png)

I wrote 'almost' because in this image you could see something:
![image](https://cloud.githubusercontent.com/assets/5699730/12127745/9df4a08a-b401-11e5-8e96-c3e8f293d2bb.png)

Any way to color the entire line, or is this out of GitGutter's scope?

**Comment by sigod** [comment]
@AviBueno What screen resolution do you use?

**Comment by AviBueno** [comment]
@sigod 1680x1050.

Seeking more info, I ran into PR #243 by @bbrks and noticed in the first screenshot that the gutter colors are neon-bright. Then I realized I'm not on 'JavaScriptNext - ES6 Syntax/Monokai Phoenix' color scheme.
Changing back to the default color scheme does make a difference, but I need to use a different color scheme than the one I'm used to and it's still not THAT easy to spot compared to an entire-line-highlighting-solution.

![image](https://cloud.githubusercontent.com/assets/5699730/12129859/0c31fa0e-b40f-11e5-96aa-7777e27277e5.png)

![image](https://cloud.githubusercontent.com/assets/5699730/12129864/1279f61e-b40f-11e5-85e8-921bba2ce04d.png)

**Comment by ndarville** [comment]
I don’t see it either for what it’s worth. Both on my Windows and macOS installations.

**Comment by deathaxe** [comment]
This issue is mainly an issue of Sublime Text itself. I does not yet scale all GUI elements correctly, which causes some elements to nearly disapear on 4k / 8k screens. So we could discuss to handle it by GitGutter or not. I am quite happy with the current solution, but can understand people, who want to have an option to make the marker more visiblie.

I was able to create a fix with only few changed lines of code to easily enable GitGutter to mark the whole line in the minimap or even resize the gutter markers locally. But this depends on the fix for Issue #340 which is not published as well due to some pending PRs.

**Comment by ndarville** [comment]
I’m not entirely sure why it’s not working on my x1080 and x900 displays (Windows/macOS), but if it’s a known issue, maybe we could start by putting it in “It's not working!?” of the README for now? <3

**Comment by deathaxe** [comment]
What is not working? GitGutter does not support different minimap marker sizes right now. You can turn them on and off only. What I descriped is a **new feature** I prepared to allow you to set the size of the marker or even highlight the whole line of the minimap.

**Comment by ndarville** [comment]
Oh I see what you mean now. It turns out there is a gutter, but my dark colour schemes obscure the 1px marker.

**Comment by deathaxe** [comment]
With GitGutter 1.5.0 the minimap size can be customized

see: `show_in_minimap` setting.

**Comment by braver** [comment]
@deathaxe is it me or does this setting not work? I tried `"show_in_minimap": 6` and `"show_in_minimap": -1`, but it all looks like a single pixel wide to me. 

- Sublime Text 3141
- Platform: osx
- Arch: x64
- GitGutter 1.7.2
- Install via PC: True
- git version 2.11.0 (Apple Git-81)
- mdpopups 2.0.0
- markdown 2.6.6
- pygments 2.1a0
- jinja2 2.8
