### ISSUE TITLE
No support for submodules

### ISSUE THREAD

**Issue by oferei** [jisaacks/GitGutter#290]
I have a git submodule within my git project. When I open a submodule file in Sublime I see plus signs beside all the lines, as if the entire content is newly added.

**Comment by oferei** [comment]
and thanks for this plugin!  ^__^

**Comment by oferei** [comment]
You assume right - git diff shows no differences.
I'm using macOS Sierra (v10.12.1) and git version 2.9.3 (Apple Git-75).

**Comment by rchl** [comment]
Is it reproducible for you on any public repo, so that I could try it locally? It works with the submodule for me in my repo.
Tried using both git 2.9.1 and git 2.7.4 (Appplie Git-66).

**Comment by oferei** [comment]
Created a brand new project on GitHub, but could not reproduce - worked as expected.
Will keep investigating.

**Comment by deathaxe** [comment]
This issue may be caused by some versions of git itself. Some git commands randomly fail, if git is not called from within the working tree, but this is exactly what GitGutter does.

I prepared a fix to run all git commands from within the working tree, which is published as soon as all required PRs are accepted.

**Comment by deathaxe** [comment]
Should work with GitGutter 1.5.0. Same as with work-tree support. Please check.

**Comment by oferei** [comment]
It works with 1.5.0!    (^O^)／
