### ISSUE TITLE
Does not support symlinked files

### ISSUE THREAD

**Issue by bootsiaz** [jisaacks/GitGutter#373]
I am working on a plugin (hdlproject) that requires symlinked files. Would someone be able to add support for this to gitgutter?

Needs a function like this:

def resolve_symlink(symlink):
  if os.path.islink(symlink):
    return os.readlink(symlink)
  else:
    return symlink

And in git_helper.py change view.file_name() to resolve_symlink(view.file_name())

**Comment by deathaxe** [comment]
You are working with GitGutter 1.4.0, right?

Please pull directly from master branch and check whether GitGutter already works for you. It makes use of `os.path.realpath(view.file_name())` to resolve symlinks since weekend. So GitGutter always works with the link source from now on and in future releases.

**Comment by bootsiaz** [comment]
Ok checked your latest build. Weird coincidence that you just started adding support. Doesn't seem to pick up the changes with the latest though. Are you sure you don't need to update git_helper.py as well?

**Comment by deathaxe** [comment]
Weird coincidence? I just like this plugin and want to share my changes to the community. So I started contributing. And your issue is about something I was working on.

Looks like `os.path.realpath()` does not correctly handle hardlinks/symlinks/junctions on Windows. On Linux I can put a link onto a file and directory and it's resolved correctly.

**Comment by bootsiaz** [comment]
Great. Thanks for your help. Are you going to update your changes to work on Windows?

**Comment by deathaxe** [comment]
If I found out how to make it work, yes. I added your lines of code, created a hardlink to a file in a repo, but it was still displayed unresolved (link instead of source). But this was a quick check only. That's why I asked for the kind of link you created. Windows supports the oooold *.lnk and NTFS makes use of junctions/symlinks/smartcopies/hardlinks. I need to dick a bit deeper into this topic and python docs for it.

**Comment by bootsiaz** [comment]
Yes, I should be more specific. The link i was using was a symbolic link, not a hard link. 

However, i do plan on using hard links on Windows in the future as it doesn't require admin privileges. So, a solution for both would be ideal.  I'm not sure how to figure out the original hard link through the os library, not sure if it's possible.

**Comment by deathaxe** [comment]
It is a still open bug of python not to resolve symlinks on windwos with `os.path.realpath()`.
See: http://bugs.python.org/issue9949

I found an inofficial patch to solve this issue.

### Hardlinks

From my current knowledge _Hardlinks_ won't be resolved. If you create a hardlink to a file this will always be an equal representation to the same set of data on disk. This is actually what Windows does since Vista with all its system files. They are stored in WinSxS but linked to where we are used to find them (System32).

Even `os.path.islink()` returns `False` for a hardlinked file.

**Comment by bootsiaz** [comment]
Thanks for looking into this!

**Comment by wggley** [comment]
+1
I work with bower link to develop some reusable modules and their files looks like new files.
On the current master branch code the simbol changed from a plus (+) to a (x)

**Comment by deathaxe** [comment]
(x) means the file is ignored.
(*) means untracked file. 
(+) is displayed on each line if the file is staged.

GitGutter uses python function `os.path.realpath` to resolve all links along the filepath, so it sees the real path any link in the path points to. The resulting path is scanned for _.git_ folder or file from bottom to top. As soon as one of the folders contains such a file, this is assumed the root of the working tree. All operations use this working tree as base.

**Comment by wggley** [comment]
Ok, In my cenario I have:
Folder A on git - OK
Real path:
C:\workspace\folderA\
Folder B symlinked by bower - NOK
Link:
C:\workspace\folderA\folderB\
Realpath
C:\worspace\folderC\folderD\folderB\

.git folder is on folderC

**Comment by wggley** [comment]
See if it's correct:
C:\workspace\folderA\.gitignore
Ignoring folderB (it's a library symlinked with it's respective repo)

But bower link is used exactly in my case that I can work one a library and test it being used and even made changes.

Not using bower link in my case demands that I change my library commit it, generate tags and after that git bower update on it. That's not productive.

**Comment by deathaxe** [comment]
Did you try with commit 57264b2f9abb3d670e576946683a7d1570448676 or current master? I ask because I realized `os.path.realpath` not to work as expected on Windows and created this commit to fix it.

To reproduce your issue, I recreated the folder structure you descriped as follows:
```
C:
+-workspace
  |
  + folderA
  | |
  | + .git
  | |
  | + folderB (symlink / junction)
  | | |
  | | + testfile
  | |
  | + .gitignore (contains /folderB)
  |
  + folderC
    |
    + .git
    |
    + folderD
      |
      + folderB (real folder)
        |
        + testfile
```

If I open _C:\workspace\folderA\folderB\testfile_ the statusbar shows _In folderC on master, File is ..._ as GitGutter resolves the symlink and uses _C:\workspace\folderC\folderD\folderB\testfile_.

So folderB is ignored in folderA, but part of the repo in folderC as expected.

I don't have bower and don't use it at all, so created the symlink of folderB using Windows' command line tool with following two alternitives:

#### Symlink

```shell
cd C:\workspace\folderA
mklink /D folderB C:\workspace\folderC\folderD\folderB
```

#### Junction

```shell
cd C:\workspace\folderA
mklink /J folderB C:\workspace\folderC\folderD\folderB
```

In both cases GitGutter shows status of _testfile_ correctly, no matter from which filesystem entry point I have a look in it.

**Comment by wggley** [comment]
Yesterday I've tried only master and it not worked, but I've tested with master and your commit and now works!

Thanks for helping this!

**Comment by wggley** [comment]
Sorry, I don't what happened but today It displays ignore character on files, look:
![print](https://cloud.githubusercontent.com/assets/13734836/23314064/0ee7f028-fa9f-11e6-8d86-1c2ca29e03a3.png)

**Comment by deathaxe** [comment]
The statusbar shows _PogoProducts_ as repository name. So GitGutter assumes C:\workspace\pogo\PogoProducts as working tree root for the open file. 

For some reason the link is not resolved.

1. I guess _pogo.cart.mobile_ is located in a repository on C:\Workspace\ as well?

2. Iguess _pogo.cart.mobile_ is handled by a different repository?

3. Can you open Sublime Text's console and enter the following line to the command line and enter it, while the file on your screenshot is open?

  ```python
  from nt import _getfinalpathname; _getfinalpathname(view.file_name()).replace('\\\\?\\', '')
  ```

This should simply print the real path of this file to the console window, if everything works as expected.

I am wondering, if this command causes any exceptions for some reason.

**Comment by deathaxe** [comment]
## Just got it!

You are running ST2. The function required to resolve symlinks on Windows is **not** supported by python 2.6, which is the scripting engine of ST2.

So sorry, I can't fix it for you. 

**Symlinks under Windows are supported with Sublime Text 3, only.**

**Comment by wggley** [comment]
Ok! Thanks for your help! I'll try to upgrade to ST3... sorry to bother

**Comment by deathaxe** [comment]
Not a problem! You couldn't know.

**Comment by deathaxe** [comment]
Symlinks are supported using pythons `os.path.realpath()` on linux and OSX.

As this function defaults to `os.path.abspath()` on Windows GitGutter 1.5.0 comes with a selfmade fix using a wndows API function.

This fix works only with python3 (ST3) and Windows Vista/7/8/8.1/10.
