### ISSUE TITLE
git rev parse fails for new git repo

### ISSUE THREAD

**Issue by rwols** [jisaacks/GitGutter#391]
When I initialize a new git repo with

```
$ git init
```
I get these errors in the console:
```
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
unloading plugin BinarySymbols.OpenCommand
generating syntax summary
GitGutter: 'git rev-parse' failed with "fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'"
GitGutter: 'git archive' failed with "fatal: Not a valid object name"
GitGutter: 'git rev-parse' failed with "fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'"
GitGutter: 'git rev-parse' failed with "fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'"
GitGutter: 'git archive' failed with "fatal: Not a valid object name"
GitGutter: 'git rev-parse' failed with "fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'"
GitGutter: 'git rev-parse' failed with "fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'"
GitGutter: 'git archive' failed with "fatal: Not a valid object name"
GitGutter: 'git rev-parse' failed with "fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'"
Skins: loading Packages/User/Saved Skins.skins failed with resource not found
GitGutter: 'git rev-parse' failed with "fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'"
```
The issue seems to persist when I add a single (first) commit.

It's gone when I add a second commit.

Can you add a check to see if the number of commits is > 1?

**Comment by deathaxe** [comment]
First of all: You don't need to be concerned about those messages. They are quite normal in your situation. They do not state a bug. I added those messages only, to enable users to hopefully provide some useful hints when faced to situations, GitGutter doesn't work as expected.

> The issue seems to persist when I add a single (first) commit.

Really? 

GitGutter uses `git rev-parse` to read the commit hash before trying to read the file content from git. This should prevent reading the whole file again and again even if it didn't change. This in fact fails, if there is no commit yet. But as soon as I add a single commit containing the new file everything is fine.

The main (design) problem at the moment is, that GitGutter tries to read and diff the file before checking whether it is tracked. 

To solve this problem I plan to use `git status` to read the branch name, commit hash and file state with a single git call before trying to read and diff the file. GitGutter won't try to read anything from the git repo then, if a file is not tracked, ignored or committed.

Means, I already have a quite stable solution on my local machine, which solves this issue. I still need to fix some edge case issues related to the 'Compare against ...' system before I want to create a pull request for public discussion, because the information got from git status are useful only, if the working file is compared to HEAD. Comparing against another branch needs some special handling.

**Comment by rwols** [comment]
Yeah, it's also not a big deal for me. Just thought I'd point it out. I'll try to give a test case for my findings about the 1 commit failing too; maybe it was just in my mind.

**Comment by deathaxe** [comment]
Absolutely ok. Thanks.

**Comment by rwols** [comment]
You were right, it doesn't spit out exceptions when I have one commit.

Another thing I noticed: If I add a new file to the project, say `b.txt`, the console reports:

```
GitGutter: 'git archive' failed with "fatal: pathspec 'b.txt' did not match any files"
```
Can you perhaps make a `sublime-settings` options called `"debug"` which is `false` by default and if `true` in the `User` settings, prints this stuff to the console? As a user I'm not really interested in errors, as long as I see my colored gutter 💯

**Comment by deathaxe** [comment]
The next version of GitGutter is intended to avoid failing git calls at all.

**Comment by rwols** [comment]
Alright, then I'm satisfied and you can close this issue if you want 👍
