### ISSUE TITLE
Since latest sublime update can no longer use tooltip because of small icons

### ISSUE THREAD

**Issue by slifin** [jisaacks/GitGutter#407]
![2017-05-08 10 25 55](https://cloud.githubusercontent.com/assets/198857/25798420/0530494a-33d9-11e7-89b1-2a6dd4c78fab.gif)

I'm using a resolution of 2560x1440
"dpi_scale": 1.6 in sublime text 
with soda theme

This wasn't an issue until the recent sublime update that changed the default sublime theme

**Comment by r-stein** [comment]
Actually the hover popup has nothing to do with the icon size and you can hover anywhere the gutter, e.g. just over the line number. You may just try to move the mouse over the line number and not move it afterwards, because the popup hides if you move your mouse away from it.
If that doesn't help please check the ST console ``ctrl+` `` for an error, which may occur.

**Comment by slifin** [comment]
Hovering on the line number and not moving the mouse produces the same result, the tooltip flickers open for a split second then closes, the icon never used to be that size so I've assumed it's all related but that might not be the case, and there's nothing that occurs in the Sublime Text console

**Comment by r-stein** [comment]
Does it also hide if you trigger it from the command palette/keybinding? I assume it registers a movement away from the popup and hides it, you can try to edit the flags in [this line](https://github.com/jisaacks/GitGutter/blob/1.6.0/modules/events.py#L111) to `'flags': 0` to avoid that.

**Comment by slifin** [comment]
yeah it shows and then immediately hides when triggering from command palette too, where should I look to find events.py?

**Comment by r-stein** [comment]
If it also directly hides from the command palette then editing that file has no use. If you open the ST console ``ctrl+` `` and execute `view.show_popup("test")` does a popup appear and persists?

**Comment by slifin** [comment]
It does in a relatively small file, in a different file that is larger (755 lines) it opens momentarily and then closes

**Comment by r-stein** [comment]
Does the hover diff popup work as expected in small files?

**Comment by slifin** [comment]
yes, it's just the icons that are tiny but the popup works as expected if I hover over the line number in the small file

**Comment by r-stein** [comment]
For the icon sizes you can try to change the [theme](https://github.com/jisaacks/GitGutter/blob/1.6.0/GitGutter.sublime-settings#L118) to `Default HiDPI.gitgutter-theme`.

**Comment by slifin** [comment]
![2017-05-08 13 39 34](https://cloud.githubusercontent.com/assets/198857/25804486/e363a530-33f3-11e7-8f0b-033ffbf54ac4.gif)
Looks a bit better still a bit off though, do you think there's something causing all pop ups to close in certain files in my installation?

**Comment by r-stein** [comment]
You can try this: https://www.sublimetext.com/docs/3/revert.html

**Comment by deathaxe** [comment]
## Diff Popup

The quickly closing popup looks like diff popup is fighting with another plugin, which tries to open a popup when hovering the gutter.

## Gutter Icons

You write about icon size being a problem since `sublime update`. Do you mean update of Sublime Text or latest GitGutter 1.6.0? **Which ST version do you use?** Many things have changed since latest ST 3127+ dev builts especially with scaling all the GUI entities.

I am running ST 3131 and GitGutter 1.6.0+ on a 1900x1200 screen on a Win10x64 box. ST 3126 is unusable with dpi_scale > 1 on my box so can't test it.

ST 3131 with "dpi_scale":1.6 gutter icons seem to be scaled correctly:

![screenshot](https://cloud.githubusercontent.com/assets/16542113/25814527/1d6f9048-341e-11e7-9dc1-9a00e19f7c3f.png)

ST 3131 with  "dpi_scale":1.0:

![screenshot](https://cloud.githubusercontent.com/assets/16542113/25814598/658410ac-341e-11e7-8fa9-853059507df1.png)

In your case not even the position of the icon is correct. It looks like scaling gutter icons does not work at all in your case.

**Comment by deathaxe** [comment]
> This wasn't an issue until the recent sublime update that changed the default sublime theme

Default theme is unchanged until 1.6.0. So I guess you pulled directly from master?

**Comment by slifin** [comment]
I meant the sublime text update, I'm using 3131 on macos

**Comment by slifin** [comment]
Looks like the interfering plugin is sublimelinter they have recently introduced a opt in tooltip 

here are the related settings in the sublime linter settings: 

```
"tooltip_fontsize": "1rem",
"tooltip_theme": "Packages/SublimeLinter/tooltip-themes/Default/Default.tooltip-theme",
"tooltip_theme_excludes": [],
"tooltips": false,
```
Still can't figure out why my icons are off centre

**Comment by slifin** [comment]
The icons still appear off centre at dpi 1.0 
<img width="58" alt="screen shot 2017-05-09 at 09 44 25" src="https://cloud.githubusercontent.com/assets/198857/25842496/20f6de96-349c-11e7-8d7d-819c6385d00d.png">

**Comment by deathaxe** [comment]
If icons display the wrong way with `dpi_scale:1.0` it is definitely an OS related issue in ST's core engine.

SublimeLinter's tooltip engine is poorly buggy. I tried to activate it, too, but instantly deactivated it as it is unusable.

**Comment by deathaxe** [comment]
@slifin : I have opened https://github.com/SublimeTextIssues/Core/issues/1713 and would ask you to help @wbond to find the reason for your issue.

**Comment by rcherny** [comment]
From my experience this quit working when SublimeLinter added their tooltip pop-ups for errors/warnings, etc. When I disable their setting for tooltips, the GitGutter tooltips work fine.

When I turn them back on, it quits working again immediately.

The size of the icons don't seem to have an impact for me, personally.

**Comment by rcherny** [comment]
Guess you guys already noted as much with SublimeLinter. Sorry for the noise.

**Comment by rcherny** [comment]
Ok in an attempt to provide something of detail: 

https://github.com/SublimeLinter/SublimeLinter3/issues/565

**Comment by deathaxe** [comment]
1. The icons were updated to ensure they are displayed correctly on HighDPI screens in ab90cfbd85918cd27a6e2b9aff195ccf27e8c2ef
2. Tooltip fighting with other packages can hardly be handled.
