### ISSUE TITLE
hide diff after git add

### ISSUE THREAD

**Issue by logig** [jisaacks/GitGutter#420]
Why not hide the diff after git add ,  just like the acting of git-bash ? Has config item for this ?

**Comment by logig** [comment]
Got it !

```
// GitGutter Settings - User

{
	"compare_against": ""
}
```
Just set "compare_against" to empty, it is strongly recommended to make this default.

**Comment by r-stein** [comment]
May be a good idea to add a "Compare Against: Index" command

**Comment by deathaxe** [comment]
@r-stein : Already done 3 months ago. But I called it "Compare against Staging Area" with `"compare_against": "CACHED"` as setting. I even declared it the default.

The reason I haven't published it were several other changes it relied on which require git 2.12.0

What @logig describes works by luck here since GitGutter uses git cat-file to read the content from the tree which uses empty object_id to indicate the staging area.

So implementing would be easy.

**Comment by logig** [comment]
I don't know, I just feel it like a "git diff xxx" command in git-bash. But this do not work fully, I have to reopen the file or it will not work. @deathaxe

**Comment by deathaxe** [comment]
The only issue with just leaving the `object_id` empty to get the file content from staging area is, We never know when it changes and thus it won't be updated after a second `git add` call. File content is read from git database only, if the commit hash changed. So this feature again needs `git status` or functions, which seem not available on older git versions.

**Comment by deathaxe** [comment]
The feature request and possible solutions to handle the staging area as compare target are discussed in #118 with same result as in this thread.

Therefore I close this issue as "duplicate".
