### ISSUE TITLE
sublime 3143 git gutter inconsistencies on scroll

### ISSUE THREAD

**Issue by joernhees** [jisaacks/GitGutter#452]
first of all thanks for gitgutter, awesome plugin.

since the latest sublime update, some of the gutter marks are lost on scroll for me: if i scroll the current region out of sight and quickly back into sight, some parts aren't marked as modified anymore. The following screenshots were taken seconds apart, nothing modified, simple scroll down and back up:
<img width="95" alt="image" src="https://user-images.githubusercontent.com/464192/30762933-536c6554-9fe4-11e7-89b5-a66abe37cab0.png"> <img width="98" alt="image" src="https://user-images.githubusercontent.com/464192/30763135-26e51cf0-9fe5-11e7-8d9a-159b8f712f56.png">

I don't see any errors in the console log, and on click or scroll left/right the gutter is redrawn and corrected... the minimap marks seem correct, making it more weird... when you grab it and quickly scroll to a region with many changes, sometimes nothing in the git gutter is marked?!?

## Support Info

- Sublime Text 3143
- Platform: osx
- Arch: x64
- GitGutter Version could not be acquired!
- Install via PC: True
- git version 2.14.1
- mdpopups 2.1.1
- markdown 2.6.9
- pygments 2.1a0
- jinja2 2.8

Already tried playing around with `debounce_delay` and `diff_algorithm`, no effect.

**Comment by deathaxe** [comment]
GitGutter doesn't update the icons by pure scrolling - only after loading/saving a file, activating a view or content modification. Therefore 

1. icons added to a line are not cleared by GitGutter in any way
2. and any changes in settings don't have any effect.

The icons and the markers in the minimap are created by the same API function `view.add_regions()`. So if the minimap markers show correctly, GitGutter seems to correctly pass the required information to ST. 

If another package temporarily adds icons to a line which has been occupied by GitGutter, GitGutter's icons are dropped, which would look like missing icons then. There are several packages out there which add icons to the gutter asynchronously. Maybe one of them is fighting with GitGutter's icons. I don't have an idea whether and how this could be related to quick scrolling. 

Could you try to setup a clean installation of ST with PC, GitGutter and its dependencies added only to check whether the issue remains?

**Comment by joernhees** [comment]
ok, closed ST, moved `~/Library/Application Support/Sublime Text 3` dir out of the way, restarted, installed PC, installed GitGutter, closed ST and restarted, same result (but agreeably much less frequent):

<img width="83" alt="screen shot 2017-09-23 at 12 19 24" src="https://user-images.githubusercontent.com/464192/30772344-a887978c-a059-11e7-8e6f-abf39b3748e3.png"> <img width="74" alt="screen shot 2017-09-23 at 12 19 12" src="https://user-images.githubusercontent.com/464192/30772343-a8872cc0-a059-11e7-8558-84d0ad8a8cce.png">

not knowing anything about how ST draws the gutter icons, but is there maybe some race condition / timeout?
As i said, i'm quite sure that this only happens since the latest ST release, did they maybe change something there?

**Comment by deathaxe** [comment]
Hmm, strange. In that case there are two last chances to find out whether the issue is caused by GitGutter.

In order to fix issue #446 GitGutter 1.7.5 uses real threads to evaluate and add the icons. ST API is considered thread safe but maybe its buggy somehow.

To check that, you could try to temporarily revert to GitGutter 1.7.4, which uses `set_timeout_async()` to do so. 

1. Download https://github.com/jisaacks/GitGutter/archive/1.7.4.zip
2. Rename it to GitGutter.sublime-package
3. Place it into `~/Library/Application Support/Sublime Text 3/Installed Packages` and replace the current one. (Hope PC doesn't update it immediately)

If the issue still remains then, you could try to use the console to add a bunch of icons and check whether they remain in the gutter after scrolling. Will create a little helper for that.

**Comment by joernhees** [comment]
if i do that ST completely freezes shortly after i try scrolling in the file

**Comment by joernhees** [comment]
ok, did some more testing by re-installing git gutter via PC, then unzipping the above link into `<subl>/Packages/`, renaming the folder to `GitGutter` and deleting the `<subl>/Installed Packages/GitGutter.sublime-package` and restarting ST... this time it comes up, GitGutter is working, but the bug remains (gutter icons disappear on scroll).

Is this maybe a ST bug?

**Comment by deathaxe** [comment]
Sorry, didn't notice the zipfile to contain a single directory with the content being downloaded. 

With the issue remaining after reverting to GitGutter 1.7.4 I am quite sure it's a bug in ST. The gutter icon rendering was updated recently to correctly support the 4k screens and fix an issue with heavy CPU usage caused by many regions added.

If we file an issue in the core section, the question will arise to create some procedure to reproduce the issue without any packages being installed. To really proof this issue is caused by the core, I would like to ask you one last thing to do.

Please move away the data directory again. Then paste the content of the code snippets from my last post to a python file within the new User directory, open a (large?) file which is not located within a git repository (to keep GitGutter disabled) and run the mentioned command from console. 

Just paste `view.run_command("debug_add_regions")`  to the console and hit enter. This will add an icon to each row in your document. If those icons get lost, too, its definitely a core issue.

**Comment by joernhees** [comment]
yepp, same problem... completely vanilla ST dir, i modified the `debug_regions.py` file to be 600 lines long though (simply newlines)

**Comment by joernhees** [comment]
problem actually also already exists with 50 lines if you make the window small and scoll fast enough... the more lines the easier though...

**Comment by deathaxe** [comment]
I can't reproduce this issue. Gutter icons are rock stable on Windows. Seems to be an OS related issue.

I've created an issue https://github.com/SublimeTextIssues/Core/issues/1947. Could you please provide information to complete the environment section?

**Comment by joernhees** [comment]
👍 thanks for debugging this...
