### ISSUE TITLE
GitGutter: "git --version" failed with "[WinError 193] %1 is not a valid Win32 application"

### ISSUE THREAD

**Issue by jayzyaj** [jisaacks/GitGutter#455]
Since I shifted to windows 10 from ubuntu in using Sublime, GitGutter and Git is working well in ubuntu. However when I tried using GitGutter in windows 10 and it doesn't work but my Git is included in my PATH and working well in PowerShell. I tried opened my console and I saw this error below.

**> GitGutter: "git --version" failed with "[WinError 193] %1 is not a valid Win32 application"**

I tried uninstalling it and install it again but still the same issue for me.

> GitGutter version: 1.7.5
> Sublime Text version: 3143
> git version 2.14.1.windows.1

Appreciate if someone can help.
Thanks in advance.

**Comment by deathaxe** [comment]
With git for windows installed and registered to the PATH and works from console, GitGutter should find it out of the box on Windows. Tried it several times on my own. The error 193 indicates, that something was found on PATH which looks like `git` executable, but doesn't seem to be one. Otherwise `WinError 2` file not found was raised.

I guess `GitGutter: Support Info` command from command panel triggers the same error?

Did you setup `"git_binary"` in either GitGutter.sublime-settings or Preferences.sublime-settings? If yes, they must point to a valid executable.  They shouldn't be required normally.

I guess it shouldn't matter, but did you mix up 32/64bit apps somehow?

Did you use git for windows setup or portable version with PATHs added manually?

By default PATH should contain `C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin` somewhere. 

If nothing helps, you can try to add `"git_binary": "C:\Program Files\Git\mingw64\bin\git.exe"` to your _Preferences.sublime-settings_ to explicitly tell GitGutter which exe to use.

**Comment by jayzyaj** [comment]
@deathaxe I installed Git via scoop in powershell. So this is my user settings in my GitGutter.

// GitGutter Settings - User

```
{
	"debug": true,
	"git_binary": "C:/Users/Jaaayz/scoop/shims/git.exe"
}
```

this is the directory of my git. But still wont work.

**Comment by deathaxe** [comment]
Works fine for me, here. What I did to check:

1. open Powershell 64-bit
2. install scoop, 
3. move my local git to an unknown path to hide it away
4. call `scoop install git`
5. set the path in GitGutter settings according to your example
6. open a repo in ST

Git is found and executed. I tried with both 32/64bit ST on Windows x64 with git 2.14.2 x64

The configuration is correct, too. Therefore I am not sure what's wrong. The "git.exe" your configuration points to is not the real git binary, but only a helper which runs git. Maybe something is wrong with it.

You could try to set `"git_binary": "C:/Users/DeathAxe/scoop/apps/git/current/mingw64/bin/git.exe"`

This is the real git.exe installed by scoop.

**Comment by jayzyaj** [comment]
Well it worked for me now using that directory. Thanks a lot! Appreciated it so much for the effort you gave!
