### ISSUE TITLE
protected_regions setting seems to make GitGutter not update alongside SublimeLinter

### ISSUE THREAD

**Issue by LeBlaaanc** [jisaacks/GitGutter#463]
Disabling these two settings seems to make GitGutter better respond when a SublimeLint issue is resolved in the editor, I'm not sure why or if this is expected. As is with defaults GitGutter needs another "refresh" for it to be accurate after a SublimeLint issue is resolved.
```json
// GitGutter Settings - User
{
    "protected_regions": [
        "sublimelinter-warning-gutter-marks", // disable?
        "sublimelinter-error-gutter-marks", // disable?
        "bookmarks",
        "lsp_error",
        "lsp_warning",
        "lsp_info"
    ],
}
```

With settings (default), notice it gets stuck not showing the modification:
![2017-10-23 11_07_25](https://user-images.githubusercontent.com/2807897/31900508-3ab6c38e-b7e4-11e7-8f11-a57bc9d1ab5b.gif)

With settings disabled:
![2017-10-23 10_57_27](https://user-images.githubusercontent.com/2807897/31900507-3aaa02d4-b7e4-11e7-813f-e28e69639954.gif)

**Comment by r-stein** [comment]
With those settings enabled GitGutter does not add an gutter icon at those positions to let SublimeLinter have the precedence in every case. If you disable it both at a gutter icon and I one of those icons will be visible. In your case the SublimeLinter icon is visible and when you remove it the hidden GitGutter icon will be shown again.
If the setting is disabled the GitGutter icon will only be added in the next GitGutter refresh.

Hence this is the expected behavior and I don't see how we can improve that (except maybe with a better understanding of the icon precedence).

**Comment by deathaxe** [comment]
Sublime Text does not provide the opportunity to apply a priority to gutter icons. You are lucky to see SublimeLinter to win the fight if both GitGutter and SublimeLinter occupy the gutter. From time to time ST seems to change the order internally which may cause SL icons to be hidden by GitGutter. 

As @r-stein correctly stated the only (hacky) way to prevent GitGutter to hide higher prior icons is to not add a region to lines, which are already occupied by one of the listed scopes.

This feature is known to be not ideal but there is no better one available at the moment (ST 3152)
