### ISSUE TITLE
Theme line

### ISSUE THREAD

**Issue by dotWaldemar** [jisaacks/GitGutter#481]
Can i do new lines for subline with border as in VSCode?

![ww](https://user-images.githubusercontent.com/25832802/35853071-3df8b8b4-0b35-11e8-96fd-91264be26fc5.png)

**Comment by deathaxe** [comment]
Not really sure, what you mean with "new lines for subline with border", but if it is about the gabs between the lines like in https://github.com/jisaacks/GitGutter/issues/433 the answer is no. 

The lines are simple icons which fill the whole possible height. The gaps are caused by the line padding settings. No chance to fill the gap.

The community asked for a dedicated gutter to highlight such kind of changes without success.
