### ISSUE TITLE
SublimeText 3 crash with a 95-100% of CPU work

### ISSUE THREAD

**Issue by MarckFp** [jisaacks/GitGutter#499]
## Description

I have a really big problem with the GitGutter plugin for SublimeText 3, I work in a large enterprise with a lot of files and is really handy to see the changes that you are doing in your files but the problem is that it uses a really big amount of CPU in my computer. I use the taks console of Windows to see the CPU work, with the Git and the GitGutter installed my use is around a 95%! if I uninstall Git or GitGutter it goes to a 15-20% of usage. That amount of CPU work makes sublime crash and freeze several times and it became impossible to work. I don't know how to fix this problem but It would be very handy if we could edit the time of refresh the check of Git, with that we could limit the use of the CPU.

Also I have to say that I work with 2 virtual machines together but it doesn't use a lot of my CPU. The values of CPU use is executing everything at the same time.

## Support Info

- Sublime Text 3176
- Platform: windows
- Arch: x64
- GitGutter 1.7.15
- Install via PC: True
- git version could not be acquired!
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue

1. First step, install git and gitgutter for SublimeText3
2. Second step take a really big amount of files in git servers and try to modify and edit some of them.
3. Third step see the Task console and watch how the cpu increases.

**Comment by deathaxe** [comment]
The amount of files open or contained by a project does not have any impact on CPU usage as GitGutter runs on the active view only. 

Maybe the size of your file can make a difference as each modification if the content needs to be saved to a temporary file on disk as git is too stupid to take it via stdin to do a diff. So if you work on very large files, saving the file after each modification can become an expensive task. 

But otherwise I can't reproduce it. Sublime Text with GitGutter enabled takes at most 10% CPU while editing a file of 200k lines of code, dropping to 0% when idle. Quickly switching between files keeps GitGutter idle in case the files did not change. If not the git commands are even finished too quick show up in the task manager. 

What means big project? I work on projects of 500MB with about 400k files without any reasonable CPU usage caused by ST or GitGutter at all.

How about RAM usage? ST tends to crash, if it hits the systems RAM limit. 

What I can suggest at the moment is:

1. Try to increase `"debounce_delay": 1000`, to reduce the number of evaluations.
2. Set `"live_mode": false` for very large files.
