### ISSUE TITLE
Interactive git rebase locks the git database creating a race condition

### ISSUE THREAD

**Issue by hadrielk** [jisaacks/GitGutter#508]
I use sublime as my git editor, and thus when I interactively rebase (`git rebase -i`), the `git-rebase-todo` file pops up in Sublime for me to edit. After making my selections and saving and closing it, I frequently (but not always) get the following:
```
$ git rebase -i @~5
fatal: Unable to create '/Users/hadrielk/code/i95b/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
could not detach HEAD
```

This appears to be related to GitGutter doing something with git in the background, because when I remove GitGutter (or use another editor for the git editor), I never get this failure. I assume GitGutter is executing some git command that locks the db temporarily, but it always seems to coincide with my closing the `git-rebase-todo` no matter how long I wait. In fact, I'm most successful in bypassing the problem by editing the todo file and closing it as fast as possible, although that might just be my impression.

This never happens with just editing my commit message in Sublime (`COMMIT_EDITMSG`).

Setting `"debug": true` yields the following:
```
GitGutter: disabled for "git-rebase-todo" because file not in a working tree
```

**Comment by deathaxe** [comment]
GitGutter sets `"GIT_OPTIONAL_LOCKS": 0` env to ask git to not lock the index as discussed in #506, already. This requires a quite recent built of git to work. Can't remember the version which starts supporting it. I use ST as git editor, too. The only situations I sometimes run into trouble are caused by ST's auto-reload feature, which locked files git wants to (re)move.

Do you have several views open which show files being modified by the rebase operation?

> my closing the git-rebase-todo no matter how long I wait. 

This might happen as closing the `git-rebase-todo` causes a view with file of the repository being activated, which triggers a status update. Means GitGutter runs some git commands for that file.

**Comment by hadrielk** [comment]
Yup, upgrading `git` did it. Thank you!
