### ISSUE TITLE
FR (Feature Request): smart annotations

### ISSUE THREAD

**Issue by KES777** [jisaacks/GitGutter#511]
## Description

Most of time we comment code, but comments are too short.
If comments are verbose they are blow the code.

So how to do much comments and keep code clean.

Now VCS become wide spread and any development without it become impossible.

Thus we can keep code annotation in repository. to start annotation we can do:

```
<<< COMMIT MESSAGE START HERE
First line is used to describe commit in short as always

FIXES #2342

The detailed info about the commit. Lorem ipsum....

#ANT: annotation for whole commit

#ANT:23-25 The annotation for 23-25 lines of commited code

#ANT:27:40-45 The annotation for 27 line from 40 to 45 character
<<<COMMIT MESSAGE END HERE
```
The gutter may blame code and select latest annotations for code lines
gutter MUST select only last annotation (get all annotations will be too expensive operation, to my mind)

Because the line 23-25 and characters 27:40-45 have annotation they should be underlined by some color to notify user that this code have annotations. Then user can move cursor to those code and activate "annotation popup" by hotkey.

The most specific annotations are displayed first.
eg. In commit history there were found two annotations:
```
#ANT:15-18 Some long text here

#ANT:17:10-20 This variable.... and the description what it mean
```
If user move cursor to line 17 pos 15. He will see two annotations:
1. The text of 17:10-20
2. The text of 15-18

`Annotations can be changed` and Gutter can provide hotkey to show previous annotation message for same line of code.
To change annotation we just specify new one for target line.
eg. The history can have two commits:
```
COMMIT 1
alksdjflkasjdfkasdf

code message alkdjf;ajdflkajdfajk 

#ANT:15-18 The updated description

COMMIT 2
asdkfjaskldfjlaj kajdflka

commit description alkdfjalskjdfklasjdflkajdf

#ANT:15-18 The initial description
```
Gutter should have hotkey to fast get previous annotation when user want to change some of them.

Gutter may be configured to display the deep of this annotations or provide hotkey to list to previous annotation.

The algorithm of changing annotation can be next:
1. User do commit
2. In commit message it writes: `ANT:25-30`
3. Press hotkey
4. gutter fills text after `ANT:25-30` and/or below lists more specific annotations: `ANT:27 text of specific annotation`
5. User deletes more specific annotation he wants leave them untouched, change descriptions, commit

To speedup things the special commits can be created with annotations. This special commit will have latest annotations for all lines of code:
```
<<<COMMIT START HERE
ANNOTATIONS

the/annotated/file
#ANT:15-18 akdjfksdjf

#ANT:17:10-20 aksdjflsjfk

another/file
#ANT:33 kdfjdjfkdjfkdjfkdjf

<<<END OF COMMIT
```
Such commits are created once by 1000 commits for example

**Comment by deathaxe** [comment]
> Such commits are created once by 1000 commits for example

This was unimportant from a developers point of view as if such a function exists it would need to work even if such comments were added/modified in each commit. Otherwise you'd find users complaining about it not to work for sure.

Commit messages in general are bound to certain file changes, which makes many ideas of your FR hard or impossible to implement using existing git concepts or functions.

Even if someone was willing to add such kind of sophisticated annotations to a commit message, the line and column numbers would be valid for this particular commit only. If content was added or removed to a file before such an annotated line in a later commit, those annotations are automatically driven invalid or would require an automatic update in the new commit message. Means highlighting them in the current version of the text file would be impossible without adding a sophisticated logic to track code changes and keep them in sync with the annotations.

Adding/deleting/editing annotations only wouldn't change a file but only the (which?) commit message and therefore not allow making a new commit. One would need to edit an existing commit message, which manipulates history. If those commits were pushed upstream already, it was even a no-go.

Highlighting annotated pieces of code would require to run a blame for the whole file and parse all the messages to finally add some `sublime.Regions` to markup the code. They'd need to be kept up to date after each file manipulation - even if not yet saved or committed.

GitGutter started to display file modifications in the gutter. All functions added over time are based on existing information, concepts and functions which are already implemented in git. GitGutter just displays  existing information or makes use of existing functions.

This FR goes far beyond that by adding additional logic to scan commits and parse their messages to extract certain tags which must play smoothly with all file changes.

This proprietary functionality would work for ST with GitGutter only. The information were useless for anybody working with other code editors or IDEs. I personally feel uncomfortable with the idea of storing annotations/comments in a separate location. 

Long sentence short: I don't think such a sophisticated functionality is within the scope of GitGutter. It was better implemented as a separate plugin.

**Comment by KES777** [comment]
The described functionality is based `git blame`.

To simplify task you can just show annotations fired by hotkey:

```
if( <hotkey> ) {
  do{
    <commit message> =  `git blame <current file>:<current line>`
  } while <commit message> not contain '#ANT';
}
```

As you can see that will be easy to implement.
