### ISSUE TITLE
show_line_annotation phantom does not support click through, preventing selection from end of line 

### ISSUE THREAD

**Issue by hsandt** [jisaacks/GitGutter#516]
## UI improvement suggestion

When show_line_annotation is "auto" (with no word wrap) or true, each line will be annotated with a phantom on the right. However, the phantom label:
1. doesn't support click through
2. occupies the whole area between the end of the current line and the end of the phantom text

Therefore, clicking between the end of the line and the end of the phantom text will not move the cursor to the end of the line (as usual when annotations are off). Actually it won't do anything since phantoms are not selectable at all.
Similarly, it's not possible to highlight text by holding the main mouse button between a position after end of the line and some position on the line.

Even if you click in the empty area between the end of the line and the phantom, you won't move the cursor to the end of the line.
Interestingly, if you click behind the phantom (to the extreme right), then it will work.

So my suggestions are:

1. The phantom should support click through
and/or
2. The phantom area should only start at the beginning of the phantom text

1 may not be possible because of limitations in Sublime Text, or because you expect clicking on the phantom to do something else, but at least 2 would allow the user to click just after the end of the line. It's much harder to click exactly after the last character to reach the end of the line or highlight an expression starting from the end.

## Support Info

- Sublime Text 3176
- Platform: linux
- Arch: x64
- GitGutter 09da5e4
- Install via PC: True
- git version 2.7.4
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue

1. Set show_line_annotation to "auto" (default) or true
2. Create or open a git project, then pick any non-empty line. If using "auto", disable word wrap.
2. Select a position on the line and wait. The annotation will appear.
3. Try to click on or highlight from after the end of the line. Nothing should happen.

![gitgutter - no click through on line annotations 2018-09-10](https://user-images.githubusercontent.com/1067772/45313022-f5651b80-b52d-11e8-8553-bfffbf65b124.gif)

**Comment by deathaxe** [comment]
ST want's the text position to know where to add the phantom. The only way to add the phantom is therefore to define the position of the linefeed to add a text. The spacing is then added via the `padding` attribute in the CSS of the underlying minihtml.

Therefore both suggestions you made are not possible with ST api.

- phantoms can not start later than with the linefeed
- phantoms can't be defined as click through

One could try to define the space between the eol and the beginning of the text as link, but this would always change the mouse cursor on hovering.

**Comment by spacesuitdiver** [comment]
@deathaxe can we not just assume a click event on the phantom should go to the end of the active line?

**Comment by deathaxe** [comment]
This was the least possible. Wouldn't enable drag select though.

**Comment by deathaxe** [comment]
While normal clicks could be handled to set the cursor to the eol, working with multiple carets could not be handled properly as modification keys such as `ctrl` are not visible to phantoms.

Introducing a link would not really fix anything properly in the end. It doesn't feel much better. This issue is to be fixed by ST core by properly handling margins of phantoms to allow click through always or by flag.

**Comment by hsandt** [comment]
1. So there is no "margin" property (an external space, not contained in the phantom area), only "padding"?
2. What if we add an extra offset of 1 or 2 characters before the phantom? It would at least allow the user to click a little on the right of the eol, without wasting too much space in case the phantom text is actually big and needs a lot of space.

**Comment by deathaxe** [comment]
1. The spacing of line annotations is actually achieved by a `margin-left` CSS property. Unfortunately this margin does not allow to click through.
2. Not possible as the positioning is done by `text point`. The most right position a phantom can be added to is the line feed. Otherwise the phantom would appear at the beginning or within the next line.

Believe me: If I knew about a proper solution I would have implemented it already.

**Comment by JaredOzzy** [comment]
I also seem to constantly run into this issue, very frustrating especially if you use a mouse.

**Comment by jonaskivi** [comment]
Today I saw the line annotation for the first time. I guess it is some new feature as I haven't seen it before...
As a feedback:
It was really distracting to have it on by default. In my opinion, it completely destroys the editing experience. Every time the user moves the cursor, this long text will pop up right after the line they are currently editing. This distracts reading and writing the code.
I think this information should be placed somewhere else, and at least not on by default.

The "line_annotation_ruler": 1, option helps a bit, as my rulers are generally not visible on screen, so I don't see it popping up, unless I resize my view. But the mouse selection issue makes it unusable anyway.

I would just leave the line annotation feature off by default (even if the selection issue would get fixed).
Otherwise GitGutter seems like a really useful tool. Thanks for making it.

**Comment by deathaxe** [comment]
This issue will be fixed for ST4 via annotations API.
