### ISSUE TITLE
After upgrading to v1.11.1, show_status_bar_text is no longer effective to disable text

### ISSUE THREAD

**Issue by gerph** [jisaacks/GitGutter#550]
## Description

After upgrading to v1.11.1, the setting ` "show_status_bar_text": false, ` is no longer effective.

With the configurations set to `false`, the status bar is still being updated according to `status_bar_text`, which it should not be.

## Support Info

```
- Sublime Text 3211
- Platform: osx
- Arch: x64
- GitGutter 1.11.1
- Install via PC: True
- git version 2.23.0
- mdpopups 3.4.0
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.10.1

Info has been copied to clipboard.
```

NOTE: The information had NOT been copied to the clipboard :-(

## Steps to Reproduce Issue

1. Configure the `show_status_bar_text` to `false`.
2. Switch to a window that is in Git.
3. Observe that the status bar contains 'Git branch: master, index: <tick>, working: <tick>` or something like that.
4. Save the file, just to make sure that it really is updating the status bar with the current configuration.

**Comment by deathaxe** [comment]
> NOTE: The information had NOT been copied to the clipboard :-(

The support info uses the Sublime Text API function `sublime.set_clipboard(msg)` to copy the generated content to the clipboard. Works well on Windows. Can't say anything about Mac as I do not have access to such a system.

Otherwise ...

1. I can't reproduce this issue on my Windows box. Status bar text correctly disappears if I set `show_status_bar_text` to `false` in the _GitGutter.sublime-settings_ or via `git_gutter_show_status_bar_text` in the _Preferences.sublime-settings_.
2. The only change made in 1.11.1 was to completely clear all cached states of a file in case it was "Saved as..." or renamed to ensure not to continue tracking it with outdated informations. 


Therefore 2 questions:

1. Do you see any error messages or `traceback ...` stuff in ST's console? 
2. In case you set `show_status_bar_text` to `false` in the _GitGutter.sublime-settings_: Do you have any project specific override or set `git_gutter_show_status_bar_text` in the _Preferences.sublime-settings_?  The latter one would override the setting in the _GitGutter.sublime-settings_.
