### ISSUE TITLE
ST4 - Line annotation background color looks ugly

### ISSUE THREAD

**Issue by pvanb** [jisaacks/GitGutter#552]
## Description

With the newest version of GitGutter the line annotations for ST4 use the background color of the current color scheme, but this looks ugly when using the ```"highlight_line": true``` option.

![Screen Shot 2020-06-19 at 7 25 33 PM](https://user-images.githubusercontent.com/823278/85185820-ae0fd100-b263-11ea-9d43-f0ee3860d2f7.png)

I propose either the background be set back to transparent (as it is in ST3) or have it be configurable in the same way the foreground is:

	"rules":
	[
		{
			"scope": "comment.line.annotation.git_gutter",
			"foreground": "#586e75",
			"background": "#073642", // or just "transparent"
		}
	]

## Support Info

- Sublime Text 4074
- Platform: osx
- Arch: x64
- GitGutter 1.11.2
- Install via PC: True
- git version 2.24.3 (Apple Git-128)
- mdpopups 3.7.1
- markdown 3.1.1
- pygments 2.1a0
- jinja2 2.10.1

**Comment by kqf** [comment]
@deathaxe I've just updated to ST4 and I am still having this issue. I probably overlooked something, but could you tell me how to fix that? 

![image](https://user-images.githubusercontent.com/4759946/147389378-ff887e73-98e3-46c2-a11d-a562d0dd9a43.png)

Another question is, why the text is so indented to the right if compared to the SBT3 version:
![image](https://user-images.githubusercontent.com/4759946/147389408-30c8d530-6468-4798-971c-f7c64bf20e53.png)

I have removed the commit has from the annotations although this didn't help much. 


## Support Info
- Sublime Text 4126
- Platform: osx
- Arch: x64
- GitGutter 1.11.7
- Install via PC: True
- git version 2.32.0 (Apple Git-132)
- mdpopups 4.2.1
- markdown not installed!
- pygments not installed!
- jinja2 2.10.1

**Comment by deathaxe** [comment]
The `transparent` background color applied by 9017050 caused rendering issues when hovering the annotation with some builts of ST4 and was therefore reverted by 8b5dd2345331f704958225dd3d6fecb46de6597d. It appears ST4126 handles them correctly again.

GitGutter uses normal phantoms when running with ST3. They suffer some edge cases with soft wrapped lines. SublimeHQ's solution for this issue is a new feature called "annotations" in ST4. These are phantoms located at the very right edge of a view, which optionally create popups when hovering. A plugin can't control the location nor the amount of text being displayed.

The `"line_annotation_ruler"` specifies whether the annotation text starts right at the end of a line or not before a ruler's column (if one is set up). GitGutter prepends spaces to achieve that. As this is used by normal phantoms, the setting applies to ST3 only.

It may be required to close and reopen a view or restart ST to make some of those settings apply after a change as GitGutter caches many of them to avoid creating required templates after every key press. As those settings don't change frequently I haven't put any effort into fixing those caching edge cases.

**Comment by kqf** [comment]
@deathaxe Thank you for taking your time to answer my questions. I understood the part about `"line_annotation_ruler"`, but I still don't know how to solve the background color issue. Is it solvable or not? 

PS: I still prefer GitGutter over the incremental diff ❤️

**Comment by deathaxe** [comment]
The background color is hardcoded. You could have a look at the commits and patch the files yourself. As most recent ST4 is able to handle `transparent` well again, I am fine to revert the latter one again.

**Comment by kqf** [comment]
Now I got it, thanks. I will play myself and probably let you know (probably tomorrow or later this week) in this thread
