### ISSUE TITLE
Gutter icon too small

### ISSUE THREAD

**Issue by snowman** [jisaacks/GitGutter#557]
## Description

The `inserted line` icon(![image](https://github.com/jisaacks/GitGutter/raw/master/docs/assets/images/gutter_inserted.png)) is too small!!!

![1604410055](https://user-images.githubusercontent.com/16096559/97990891-8dfc3b00-1e1b-11eb-98cd-aa21977ae15d.png)

## Support Info
```
- Sublime Text 3211
- Platform: linux
- Arch: x64
- GitGutter 1.11.3
- Install via PC: True
- git version 2.29.2
- mdpopups 3.7.5
- markdown 3.1.1
- pygments 2.1a0
- jinja2 2.10.1
```

**Comment by deathaxe** [comment]
Gutter icons are png files. The size is controlled by ST. Based on `ui_scale` ST selects the appropriate resource file `inserted.png` or `inserted@2x.png` and should scale it to the needed size. That's the case for all kinds of gutter icons.

Changing the `font_size` setting doesn't have any effect on those gutter icons.

If your screen resolution is 8k it might be caused by missing `inserted@4x.png` files. Would need someone to create those then.

Otherwise I don't know why ST wouldn't render the gutter icon with the same size as the status badge in the sidebar, which basically is a png file, too.
