### ISSUE TITLE
How to disable key bindings?

### ISSUE THREAD

**Issue by khamaileon** [jisaacks/GitGutter#558]
How to disable key bindings?
I lost 1h of work because of it :(

**Comment by deathaxe** [comment]
The same way you'd do that for all key bindings provided by ST out of the box or any plugin.

You may want to add a rule to your user file for the binding in question and point it to `noop` command.

Otherwise I'd be curious, why one would loose work due to a key binding.

The only text manipulating one is `git_gutter_revert_change`, which performs a normal edit operation. In case it happens by accident it can easily be undone via ST's undo command (`ctrl+z`).

Please also note that ST3207+ also defines key bindings with nearly the same meaning!

```
	{ "keys": ["ctrl+k", "ctrl+z"], "command": "revert_hunk" },
	{ "keys": ["ctrl+k", "ctrl+shift+z"], "command": "revert_modification" },
```
