### ISSUE TITLE
Allow formatting of line_author_time

### ISSUE THREAD

**Issue by wasmitnetzen** [jisaacks/GitGutter#562]
## Description

Currently, the time string for `line_author_time` and `line_committer_time` is [hard coded](https://github.com/jisaacks/GitGutter/blob/9ca46d926a8a8eb6abf58d546002aef34cd174b0/modules/blame.py#L130) to the format `%b %d %Y %H:%M`. It would be nice to be able to format this differently. It could respect the [LC_TIME](https://man.archlinux.org/man/locale.5#LC_TIME) variable, or just accept any valid format string in the plugin settings.

## Support Info

- Sublime Text 4107
- Platform: linux
- Arch: x64
- GitGutter 1.11.4
- Install via PC: True
- git version 2.27.0
- mdpopups 4.1.1
- markdown 3.2.2
- pygments 2.1a0
- jinja2 2.10.1

**Comment by iahu** [comment]
the `%s` formate string is not works correctly for me. It maybe due to the Python.

Expect the `%s` formate will output time string as `Year` `Month` `Date` order, but still got `Date` `Month` `Year` order.

Hope to support a custom setting for that.

Thanks.


## Support Info

- Sublime Text 4143
- Platform: osx
- Arch: arm64
- GitGutter 1.11.7
- Install via PC: True
- git version 2.36.1
- mdpopups 4.2.2
- markdown 3.2.2
- pygments 2.1a0
- jinja2 2.10.1
