### ISSUE TITLE
Set `non_blocking` to true by default

### ISSUE THREAD

**Issue by jamwaffles** [jisaacks/GitGutter#75]
One of Sublime Text 3's main features is asynchronous plugins. In addition, one doesn't need Git diff changes _immediately_ after modifying the file, so why isn't `non_blocking` set to true by default?

**Comment by lgarron** [comment]
> simply because it lags sublime if it's blocking.

Indeed, I'm finding this a bit frustrating. GitGutter is perfectly usable for most files, but I when I open a a medium-size file (≈10,000 lines) Sublime quickly becomes unusable. I still can't tell if I've configured `non_blocking` correctly (the README mentions the setting, but not an explicit example of a settings file), so I end up disabling and enabling GitGutter several times a day.

(And disabling takes 10 seconds, because of the delay due to GitGutter.)

**Comment by lgarron** [comment]
> I still can't tell if I've configured non_blocking correctly

I just looked into it a little, and found I also need `"focus_change_mode": false` in order to avoid locking up Sublime when I switch to those files. But I still see a beachball for one second when I save.
